using System.Text;
using Pal.Engine.Model;
using Pal.Engine.Scoring;
using Pal.Reporting.Json;

namespace Pal.Reporting.Html;

public static class HtmlReportWriter
{
    public static void Write(JsonReportWriter.WriteInput input, string htmlPath) =>
        File.WriteAllText(htmlPath, BuildHtml(input), new UTF8Encoding(false));

    public static void WriteToStream(JsonReportWriter.WriteInput input, Stream destination)
    {
        using var writer = new StreamWriter(destination, new UTF8Encoding(false), leaveOpen: true);
        writer.Write(BuildHtml(input));
    }

    private static string BuildHtml(JsonReportWriter.WriteInput input)
    {
        var sb = new StringBuilder();
        var overall = StatusClassifier.ClassifyOverall(input.Findings);
        string statusColor = overall == ReportStatus.Critical ? "#d32f2f"
            : overall == ReportStatus.Warning ? "#f57c00" : "#388e3c";
        string statusText = overall.ToString().ToUpperInvariant();

        string machineName = input.Dataset.MachineName ?? "Unknown";
        string timeRange = $"{input.Dataset.StartTimeUtc:yyyy-MM-dd HH:mm}Z – {input.Dataset.EndTimeUtc:yyyy-MM-dd HH:mm}Z";

        sb.AppendLine("<!DOCTYPE html>");
        sb.AppendLine("<html lang=\"en\">");
        sb.AppendLine("<head>");
        sb.AppendLine("<meta charset=\"UTF-8\">");
        sb.AppendLine("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
        sb.AppendLine($"<title>PAL Report — {machineName}</title>");
        sb.AppendLine("<style>");
        sb.AppendLine(GetStyles());
        sb.AppendLine("</style>");
        sb.AppendLine("</head><body>");

        sb.AppendLine("<div class=\"header\">");
        sb.AppendLine($"<h1>PAL Performance Analysis Report</h1>");
        sb.AppendLine($"<p>Machine: <strong>{Escape(machineName)}</strong> &nbsp;|&nbsp; {Escape(timeRange)}</p>");
        sb.AppendLine($"<p>Overall Status: <span class=\"status\" style=\"background:{statusColor}\">{statusText}</span></p>");
        sb.AppendLine("</div>");

        sb.AppendLine("<div class=\"section\">");
        sb.AppendLine("<h2>Summary</h2>");
        sb.AppendLine("<table class=\"summary-table\">");
        sb.AppendLine("<tr><th>Severity</th><th>Count</th></tr>");
        int criticals = input.Findings.Count(f => f.Severity == "critical");
        int warnings = input.Findings.Count(f => f.Severity == "warning");
        int infos = input.Findings.Count(f => f.Severity == "informational");
        sb.AppendLine($"<tr class=\"sev-critical\"><td>Critical</td><td>{criticals}</td></tr>");
        sb.AppendLine($"<tr class=\"sev-warning\"><td>Warning</td><td>{warnings}</td></tr>");
        sb.AppendLine($"<tr><td>Informational</td><td>{infos}</td></tr>");
        sb.AppendLine("</table></div>");

        if (input.Findings.Count == 0)
        {
            sb.AppendLine("<div class=\"section\"><p class=\"healthy\">✔ No findings. The analyzed dataset is within expected parameters.</p></div>");
        }
        else
        {
            sb.AppendLine("<div class=\"section\">");
            sb.AppendLine("<h2>Findings</h2>");
            foreach (var f in input.Findings)
                RenderFinding(sb, f);
            sb.AppendLine("</div>");
        }

        if (input.EngineWarnings.Count > 0 || input.CollectorWarnings.Count > 0)
        {
            sb.AppendLine("<div class=\"section\">");
            sb.AppendLine("<h2>Warnings</h2><ul>");
            foreach (var w in input.CollectorWarnings)
                sb.AppendLine($"<li>{Escape(w)}</li>");
            foreach (var w in input.EngineWarnings)
                sb.AppendLine($"<li>[{Escape(w.Code)}] {Escape(w.Message)}</li>");
            sb.AppendLine("</ul></div>");
        }

        sb.AppendLine("<div class=\"footer\">");
        sb.AppendLine($"<p>Generated by PAL 2026.2.0 at {input.GeneratedAt:yyyy-MM-ddTHH:mm:ssZ}</p>");
        sb.AppendLine("<p>PAL thresholds are guidelines. Results require context-specific interpretation.</p>");
        sb.AppendLine("</div>");
        sb.AppendLine("</body></html>");

        return sb.ToString();
    }

    private static void RenderFinding(StringBuilder sb, Finding f)
    {
        string sevClass = f.Severity == "critical" ? "sev-critical" : f.Severity == "warning" ? "sev-warning" : "sev-info";
        sb.AppendLine($"<div class=\"finding {sevClass}\">");
        sb.AppendLine($"<h3>{Escape(f.Title)} <span class=\"badge {sevClass}\">{f.Severity.ToUpperInvariant()}</span></h3>");
        sb.AppendLine($"<p><strong>Category:</strong> {Escape(f.Category)} &nbsp;|&nbsp; <strong>Rule:</strong> {Escape(f.RuleId)} &nbsp;|&nbsp; <strong>Pack:</strong> {Escape(f.PackId)}</p>");
        sb.AppendLine($"<p>{Escape(f.Summary)}</p>");
        if (!string.IsNullOrWhiteSpace(f.Explanation))
            sb.AppendLine($"<p class=\"explanation\">{Escape(f.Explanation)}</p>");

        if (f.EvidenceMetrics.Count > 0)
        {
            sb.AppendLine("<table class=\"evidence-table\">");
            sb.AppendLine("<tr><th>Metric</th><th>Avg</th><th>Max</th><th>P95</th><th>Condition</th></tr>");
            foreach (var m in f.EvidenceMetrics)
            {
                var s = m.Statistics;
                string expr = m.TriggerDetails.FirstOrDefault()?.Expression ?? "";
                sb.AppendLine($"<tr><td>{Escape(m.CanonicalMetric)}</td><td>{s.Avg:F2}</td><td>{s.Max:F2}</td><td>{s.P95:F2}</td><td>{Escape(expr)}</td></tr>");
            }
            sb.AppendLine("</table>");
        }

        if (f.Recommendations.Count > 0)
        {
            sb.AppendLine("<h4>Recommendations</h4><ol>");
            foreach (var r in f.Recommendations)
                sb.AppendLine($"<li><strong>[{r.Priority.ToUpperInvariant()}]</strong> {Escape(r.Text)}</li>");
            sb.AppendLine("</ol>");
        }
        sb.AppendLine("</div>");
    }

    private static string Escape(string? text) =>
        System.Net.WebUtility.HtmlEncode(text ?? string.Empty);

    private static string GetStyles() => """
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; background: #f5f5f5; color: #222; }
        .header { background: #1a237e; color: white; padding: 24px 40px; }
        .header h1 { margin: 0 0 8px; font-size: 1.6em; }
        .header p { margin: 4px 0; opacity: 0.9; }
        .status { display: inline-block; padding: 4px 12px; border-radius: 4px; color: white; font-weight: bold; font-size: 0.9em; }
        .section { background: white; margin: 16px 40px; padding: 20px 24px; border-radius: 6px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
        .section h2 { margin-top: 0; border-bottom: 1px solid #eee; padding-bottom: 8px; }
        .summary-table { border-collapse: collapse; }
        .summary-table th, .summary-table td { padding: 6px 16px; text-align: left; border: 1px solid #ddd; }
        .finding { border-left: 5px solid #ccc; margin: 12px 0; padding: 16px; border-radius: 4px; background: #fafafa; }
        .finding h3 { margin-top: 0; }
        .badge { font-size: 0.7em; padding: 2px 8px; border-radius: 3px; color: white; vertical-align: middle; }
        .sev-critical { border-color: #d32f2f; }
        .sev-critical.badge, td.sev-critical { background: #d32f2f; }
        .sev-warning { border-color: #f57c00; }
        .sev-warning.badge, td.sev-warning { background: #f57c00; }
        .sev-info { border-color: #0288d1; }
        .evidence-table { border-collapse: collapse; width: 100%; margin: 8px 0; font-size: 0.9em; }
        .evidence-table th, .evidence-table td { border: 1px solid #ddd; padding: 5px 10px; }
        .evidence-table th { background: #f5f5f5; }
        .explanation { color: #555; font-size: 0.95em; }
        .healthy { color: #388e3c; font-weight: bold; }
        .footer { background: white; margin: 16px 40px 32px; padding: 16px 24px; border-radius: 6px; font-size: 0.85em; color: #777; }
        """;
}
