// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pal.Persistence;

#nullable disable

namespace Pal.Persistence.Migrations
{
    [DbContext(typeof(PalDbContext))]
    [Migration("20260425180839_Phase3aCompareBaselines")]
    partial class Phase3aCompareBaselines
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pal.Persistence.Entities.AnalysisJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaselineLabel")
                        .HasColumnType("text")
                        .HasColumnName("baseline_label");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ContextJson")
                        .HasColumnType("text")
                        .HasColumnName("context_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<bool>("IsBaseline")
                        .HasColumnType("boolean")
                        .HasColumnName("is_baseline");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("text")
                        .HasColumnName("options_json");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("UploadId")
                        .HasColumnType("uuid")
                        .HasColumnName("upload_id");

                    b.HasKey("Id")
                        .HasName("pk_analysis_jobs");

                    b.HasIndex("UploadId")
                        .HasDatabaseName("ix_analysis_jobs_upload_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_analysis_jobs_status_created_at");

                    b.ToTable("analysis_jobs", (string)null);
                });

            modelBuilder.Entity("Pal.Persistence.Entities.AnalysisJobPackEntity", b =>
                {
                    b.Property<Guid>("AnalysisJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_job_id");

                    b.Property<string>("PackId")
                        .HasColumnType("text")
                        .HasColumnName("pack_id");

                    b.Property<string>("PackVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pack_version");

                    b.HasKey("AnalysisJobId", "PackId")
                        .HasName("pk_analysis_job_packs");

                    b.ToTable("analysis_job_packs", (string)null);
                });

            modelBuilder.Entity("Pal.Persistence.Entities.AnalysisReportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnalysisJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_job_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("format");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.HasKey("Id")
                        .HasName("pk_analysis_reports");

                    b.HasIndex("AnalysisJobId")
                        .HasDatabaseName("ix_analysis_reports_analysis_job_id");

                    b.ToTable("analysis_reports", (string)null);
                });

            modelBuilder.Entity("Pal.Persistence.Entities.AnalysisResultEntity", b =>
                {
                    b.Property<Guid>("AnalysisJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_job_id");

                    b.Property<string>("FindingsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("findings_json");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<string>("SummaryJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary_json");

                    b.HasKey("AnalysisJobId")
                        .HasName("pk_analysis_results");

                    b.ToTable("analysis_results", (string)null);
                });

            modelBuilder.Entity("Pal.Persistence.Entities.AuditEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_id");

                    b.Property<string>("EventJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_json");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("EventType", "CreatedAt")
                        .HasDatabaseName("ix_audit_events_event_type_created_at");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("Pal.Persistence.Entities.CompareResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BaselineJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("baseline_job_id");

                    b.Property<Guid>("CandidateJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_job_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result_json");

                    b.HasKey("Id")
                        .HasName("pk_compare_results");

                    b.HasIndex("BaselineJobId")
                        .HasDatabaseName("ix_compare_results_baseline_job_id");

                    b.HasIndex("CandidateJobId")
                        .HasDatabaseName("ix_compare_results_candidate_job_id");

                    b.ToTable("compare_results", (string)null);
                });

            modelBuilder.Entity("Pal.Persistence.Entities.PackEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_packs");

                    b.ToTable("packs", (string)null);
                });

            modelBuilder.Entity("Pal.Persistence.Entities.PackVersionEntity", b =>
                {
                    b.Property<string>("PackId")
                        .HasColumnType("text")
                        .HasColumnName("pack_id");

                    b.Property<string>("Version")
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.HasKey("PackId", "Version")
                        .HasName("pk_pack_versions");

                    b.ToTable("pack_versions", (string)null);
                });

            modelBuilder.Entity("Pal.Persistence.Entities.UploadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_type");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.HasKey("Id")
                        .HasName("pk_uploads");

                    b.HasIndex("Sha256")
                        .IsUnique()
                        .HasDatabaseName("ix_uploads_sha256");

                    b.ToTable("uploads", (string)null);
                });

            modelBuilder.Entity("Pal.Persistence.Entities.AnalysisJobEntity", b =>
                {
                    b.HasOne("Pal.Persistence.Entities.UploadEntity", "Upload")
                        .WithMany("AnalysisJobs")
                        .HasForeignKey("UploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_analysis_jobs_uploads_upload_id");

                    b.Navigation("Upload");
                });

            modelBuilder.Entity("Pal.Persistence.Entities.AnalysisJobPackEntity", b =>
                {
                    b.HasOne("Pal.Persistence.Entities.AnalysisJobEntity", "AnalysisJob")
                        .WithMany("Packs")
                        .HasForeignKey("AnalysisJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_analysis_job_packs_analysis_jobs_analysis_job_id");

                    b.Navigation("AnalysisJob");
                });

            modelBuilder.Entity("Pal.Persistence.Entities.AnalysisReportEntity", b =>
                {
                    b.HasOne("Pal.Persistence.Entities.AnalysisJobEntity", "AnalysisJob")
                        .WithMany("Reports")
                        .HasForeignKey("AnalysisJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_analysis_reports_analysis_jobs_analysis_job_id");

                    b.Navigation("AnalysisJob");
                });

            modelBuilder.Entity("Pal.Persistence.Entities.AnalysisResultEntity", b =>
                {
                    b.HasOne("Pal.Persistence.Entities.AnalysisJobEntity", "AnalysisJob")
                        .WithOne("Result")
                        .HasForeignKey("Pal.Persistence.Entities.AnalysisResultEntity", "AnalysisJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_analysis_results_analysis_jobs_analysis_job_id");

                    b.Navigation("AnalysisJob");
                });

            modelBuilder.Entity("Pal.Persistence.Entities.CompareResultEntity", b =>
                {
                    b.HasOne("Pal.Persistence.Entities.AnalysisJobEntity", "BaselineJob")
                        .WithMany()
                        .HasForeignKey("BaselineJobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_compare_results_analysis_jobs_baseline_job_id");

                    b.HasOne("Pal.Persistence.Entities.AnalysisJobEntity", "CandidateJob")
                        .WithMany()
                        .HasForeignKey("CandidateJobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_compare_results_analysis_jobs_candidate_job_id");

                    b.Navigation("BaselineJob");

                    b.Navigation("CandidateJob");
                });

            modelBuilder.Entity("Pal.Persistence.Entities.PackVersionEntity", b =>
                {
                    b.HasOne("Pal.Persistence.Entities.PackEntity", "Pack")
                        .WithMany("Versions")
                        .HasForeignKey("PackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pack_versions_packs_pack_id");

                    b.Navigation("Pack");
                });

            modelBuilder.Entity("Pal.Persistence.Entities.AnalysisJobEntity", b =>
                {
                    b.Navigation("Packs");

                    b.Navigation("Reports");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("Pal.Persistence.Entities.PackEntity", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Pal.Persistence.Entities.UploadEntity", b =>
                {
                    b.Navigation("AnalysisJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
