using System.Text;
using Pal.Engine.Scoring;
using Pal.Reporting.Json;

namespace Pal.Reporting.Markdown;

public sealed class MarkdownReportWriter
{
    public void Write(JsonReportWriter.WriteInput input, string outputPath) =>
        File.WriteAllText(outputPath, BuildMarkdown(input), new UTF8Encoding(false));

    public void WriteToStream(JsonReportWriter.WriteInput input, Stream destination)
    {
        using var writer = new StreamWriter(destination, new UTF8Encoding(false), leaveOpen: true);
        writer.Write(BuildMarkdown(input));
    }

    private static string BuildMarkdown(JsonReportWriter.WriteInput input)
    {
        var sb = new StringBuilder();
        var overall = StatusClassifier.ClassifyOverall(input.Findings);
        string statusText = overall.ToString().ToUpperInvariant();
        string machineName = input.Dataset.MachineName ?? "Unknown";
        string timeRange = $"{input.Dataset.StartTimeUtc:yyyy-MM-dd HH:mm}Z – {input.Dataset.EndTimeUtc:yyyy-MM-dd HH:mm}Z";

        sb.AppendLine("# PAL Performance Analysis Report");
        sb.AppendLine();
        sb.AppendLine($"| Field | Value |");
        sb.AppendLine($"|---|---|");
        sb.AppendLine($"| Machine | `{machineName}` |");
        sb.AppendLine($"| Time Range | {timeRange} |");
        sb.AppendLine($"| Overall Status | **{statusText}** |");
        sb.AppendLine($"| Generated | {input.GeneratedAt:yyyy-MM-ddTHH:mm:ssZ} |");
        sb.AppendLine();

        int criticals = input.Findings.Count(f => f.Severity == "critical");
        int warnings = input.Findings.Count(f => f.Severity == "warning");
        int infos = input.Findings.Count(f => f.Severity == "informational");

        sb.AppendLine("## Summary");
        sb.AppendLine();
        sb.AppendLine("| Severity | Count |");
        sb.AppendLine("|---|---|");
        sb.AppendLine($"| Critical | {criticals} |");
        sb.AppendLine($"| Warning | {warnings} |");
        sb.AppendLine($"| Informational | {infos} |");
        sb.AppendLine();

        if (input.Findings.Count == 0)
        {
            sb.AppendLine("> ✔ No findings. The analyzed dataset is within expected parameters.");
            sb.AppendLine();
        }
        else
        {
            sb.AppendLine("## Findings");
            sb.AppendLine();
            foreach (var f in input.Findings)
            {
                sb.AppendLine($"### [{f.Severity.ToUpperInvariant()}] {f.Title}");
                sb.AppendLine();
                sb.AppendLine($"| Field | Value |");
                sb.AppendLine($"|---|---|");
                sb.AppendLine($"| Rule | `{f.RuleId}` |");
                sb.AppendLine($"| Pack | `{f.PackId}` |");
                sb.AppendLine($"| Category | {EscapePipe(f.Category)} |");
                sb.AppendLine();
                sb.AppendLine(f.Summary);
                sb.AppendLine();
                if (!string.IsNullOrWhiteSpace(f.Explanation))
                {
                    sb.AppendLine($"> {f.Explanation}");
                    sb.AppendLine();
                }

                if (f.EvidenceMetrics.Count > 0)
                {
                    sb.AppendLine("**Evidence**");
                    sb.AppendLine();
                    sb.AppendLine("| Metric | Avg | Max | P95 | Condition |");
                    sb.AppendLine("|---|---|---|---|---|");
                    foreach (var m in f.EvidenceMetrics)
                    {
                        var s = m.Statistics;
                        string expr = m.TriggerDetails.FirstOrDefault()?.Expression ?? "";
                        sb.AppendLine($"| `{m.CanonicalMetric}` | {s.Avg:F2} | {s.Max:F2} | {s.P95:F2} | {EscapePipe(expr)} |");
                    }
                    sb.AppendLine();
                }

                if (f.Recommendations.Count > 0)
                {
                    sb.AppendLine("**Recommendations**");
                    sb.AppendLine();
                    foreach (var r in f.Recommendations)
                        sb.AppendLine($"- [{r.Priority.ToUpperInvariant()}] {r.Text}");
                    sb.AppendLine();
                }
            }
        }

        if (input.EngineWarnings.Count > 0 || input.CollectorWarnings.Count > 0)
        {
            sb.AppendLine("## Warnings");
            sb.AppendLine();
            foreach (var w in input.CollectorWarnings)
                sb.AppendLine($"- {w}");
            foreach (var w in input.EngineWarnings)
                sb.AppendLine($"- `[{w.Code}]` {w.Message}");
            sb.AppendLine();
        }

        sb.AppendLine("---");
        sb.AppendLine();
        sb.AppendLine("*Generated by PAL 2026.2.0. Thresholds are guidelines — results require context-specific interpretation.*");

        return sb.ToString();
    }

    private static string EscapePipe(string s) => s.Replace("|", "\\|");
}
